#!/usr/bin/env bash
set -e

# source in helper functions
source "$( dirname "${BASH_SOURCE[0]}" )/helpers/helpers.sh"

# Check if required tools are available
ensureMake
ensureForge
ensureDocker

# Build the contracts and dependencies
log "Building AVS performer..."
BUILD_CONTAINER=true ./.hourglass/scripts/build.sh >&2

log "Building contracts..."
cd .devkit/contracts && forge clean && forge build -- --include ../../contracts/**/*.sol >&2

log "Build completed successfully." 
