[profile.default]
src = "src"
out = "out"
libs = ["lib", "../../contracts"]
fs_permissions = [{ access = "read-write", path = "./"}]
show_progress=true
gas_reports = ["*"]

# Defines paths for Solidity imports.
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@hourglass-monorepo/=lib/hourglass-monorepo/contracts/",
    "@eigenlayer-middleware/=lib/hourglass-monorepo/contracts/lib/eigenlayer-middleware/",
    "@eigenlayer-contracts/=lib/hourglass-monorepo/contracts/lib/eigenlayer-middleware/lib/eigenlayer-contracts/",
    "@openzeppelin/=lib/hourglass-monorepo/contracts/lib/eigenlayer-middleware/lib/openzeppelin-contracts/",
    "@openzeppelin-upgrades/=lib/hourglass-monorepo/contracts/lib/eigenlayer-middleware/lib/openzeppelin-contracts-upgradeable/",
    "@project/=../../contracts/src/",
]

# Specifies the exact version of Solidity to use, overriding auto-detection.
solc_version = '0.8.27'
# If set to true, changes compilation pipeline to go through the new IR optimizer.
via_ir = false
# Whether or not to enable the Solidity optimizer.
optimizer = true
# The number of runs specifies roughly how often each opcode of the deployed code will be executed 
# across the life-time of the contract. This means it is a trade-off parameter between code size (deploy cost) 
# and code execution cost (cost after deployment).
optimizer_runs = 200

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
holesky = "${RPC_HOLESKY}"

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 120
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
