version: 0.0.1
config:
    project:
        name: hello-devkit
        version: 0.1.0
        context: devnet
        templateBaseUrl: https://github.com/Layr-Labs/hourglass-avs-template
        templateVersion: v0.0.12
